import { describe, expect, test } from 'vitest'

import { parseChecksums } from '../../../src/http-request/checksums'

const HASH_A =
  'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
const HASH_B =
  '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'

describe.sequential('http-request/checksums — parseChecksums', () => {
  test('parses GNU two-space format', () => {
    expect(parseChecksums(`${HASH_A}  file.zip\n`)).toEqual({
      'file.zip': HASH_A,
    })
  })

  test('parses GNU single-space format (the regex tolerates either)', () => {
    expect(parseChecksums(`${HASH_A} file.zip\n`)).toEqual({
      'file.zip': HASH_A,
    })
  })

  test('parses BSD format ("SHA256 (filename) = hash")', () => {
    expect(parseChecksums(`SHA256 (file.zip) = ${HASH_A}\n`)).toEqual({
      'file.zip': HASH_A,
    })
  })

  test('lowercases hex digits', () => {
    expect(
      parseChecksums(
        `E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855  file.zip\n`,
      ),
    ).toEqual({ 'file.zip': HASH_A })
  })

  test('handles multiple entries', () => {
    const text = `${HASH_A}  a.zip\n${HASH_B}  b.tar.gz\n`
    expect(parseChecksums(text)).toEqual({
      'a.zip': HASH_A,
      'b.tar.gz': HASH_B,
    })
  })

  test('skips blank lines', () => {
    const text = `\n${HASH_A}  a.zip\n\n\n`
    expect(parseChecksums(text)).toEqual({ 'a.zip': HASH_A })
  })

  test('skips comment lines starting with #', () => {
    const text = `# Generated by sha256sum\n# DO NOT EDIT\n${HASH_A}  a.zip\n`
    expect(parseChecksums(text)).toEqual({ 'a.zip': HASH_A })
  })

  test('ignores lines that match neither format', () => {
    const text = `garbage line\n${HASH_A}  a.zip\nmore garbage\n`
    expect(parseChecksums(text)).toEqual({ 'a.zip': HASH_A })
  })

  test('returns empty object on empty input', () => {
    expect(parseChecksums('')).toEqual({})
  })

  test('handles filenames with spaces (GNU regex is greedy on the filename half)', () => {
    expect(parseChecksums(`${HASH_A}  file with spaces.zip\n`)).toEqual({
      'file with spaces.zip': HASH_A,
    })
  })

  test('mixed BSD and GNU lines in one file', () => {
    const text = `SHA256 (a.zip) = ${HASH_A}\n${HASH_B}  b.tar.gz\n`
    expect(parseChecksums(text)).toEqual({
      'a.zip': HASH_A,
      'b.tar.gz': HASH_B,
    })
  })

  test('ignores hashes that are not 64 hex chars', () => {
    // Too short, too long, or contains non-hex.
    expect(parseChecksums('abc123  short.zip\n')).toEqual({})
  })
})
