import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'

import { parseChecksumFile } from '../../../src/http-request/checksum-file'

vi.mock(import('../../../src/http-request/request'), () => ({
  httpRequest: vi.fn(),
}))

async function loadFresh() {
  const reqMod = await import('../../../src/http-request/request')
  const mod = await import('../../../src/http-request/checksum-file')
  return {
    httpRequest: reqMod.httpRequest as ReturnType<typeof vi.fn>,
    fetchChecksumFile: mod.fetchChecksumFile,
  }
}

function makeResponse(opts: {
  ok: boolean
  status?: number | undefined
  body: string
}) {
  const { body, ok, status = ok ? 200 : 500 } = opts
  return {
    ok,
    status,
    statusText: ok ? 'OK' : 'Error',
    headers: {},
    body: Buffer.from(body),
    text: () => body,
    json: <T,>() => JSON.parse(body) as T,
    arrayBuffer: () => new ArrayBuffer(0),
    rawResponse: undefined,
  }
}

const HASH_A =
  'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
const HASH_B =
  '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
const INT_A = 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='
const INT_B = 'sha256-ASNFZ4mrze8BI0VniavN7wEjRWeJq83vASNFZ4mrze8='

describe.sequential('http-request/checksums — parseChecksumFile', () => {
  test('parses GNU two-space format', () => {
    expect(parseChecksumFile(`${HASH_A}  file.zip\n`)).toEqual({
      'file.zip': INT_A,
    })
  })

  test('parses GNU single-space format (the regex tolerates either)', () => {
    expect(parseChecksumFile(`${HASH_A} file.zip\n`)).toEqual({
      'file.zip': INT_A,
    })
  })

  test('parses BSD format ("SHA256 (filename) = hash")', () => {
    expect(parseChecksumFile(`SHA256 (file.zip) = ${HASH_A}\n`)).toEqual({
      'file.zip': INT_A,
    })
  })

  test('lowercases hex digits before converting to integrity', () => {
    expect(
      parseChecksumFile(
        `E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855  file.zip\n`,
      ),
    ).toEqual({ 'file.zip': INT_A })
  })

  test('handles multiple entries', () => {
    const text = `${HASH_A}  a.zip\n${HASH_B}  b.tar.gz\n`
    expect(parseChecksumFile(text)).toEqual({
      'a.zip': INT_A,
      'b.tar.gz': INT_B,
    })
  })

  test('skips blank lines', () => {
    const text = `\n${HASH_A}  a.zip\n\n\n`
    expect(parseChecksumFile(text)).toEqual({ 'a.zip': INT_A })
  })

  test('skips comment lines starting with #', () => {
    const text = `# Generated by sha256sum\n# DO NOT EDIT\n${HASH_A}  a.zip\n`
    expect(parseChecksumFile(text)).toEqual({ 'a.zip': INT_A })
  })

  test('ignores lines that match neither format', () => {
    const text = `garbage line\n${HASH_A}  a.zip\nmore garbage\n`
    expect(parseChecksumFile(text)).toEqual({ 'a.zip': INT_A })
  })

  test('returns empty object on empty input', () => {
    expect(parseChecksumFile('')).toEqual({})
  })

  test('handles filenames with spaces (GNU regex is greedy on the filename half)', () => {
    expect(parseChecksumFile(`${HASH_A}  file with spaces.zip\n`)).toEqual({
      'file with spaces.zip': INT_A,
    })
  })

  test('mixed BSD and GNU lines in one file', () => {
    const text = `SHA256 (a.zip) = ${HASH_A}\n${HASH_B}  b.tar.gz\n`
    expect(parseChecksumFile(text)).toEqual({
      'a.zip': INT_A,
      'b.tar.gz': INT_B,
    })
  })

  test('ignores hashes that are not 64 hex chars', () => {
    expect(parseChecksumFile('abc123  short.zip\n')).toEqual({})
  })
})

beforeEach(() => {
  vi.resetModules()
})

afterEach(() => {
  vi.clearAllMocks()
})

describe.sequential('http-request/checksums — fetchChecksumFile', () => {
  test('parses the response body into a checksums map', async () => {
    const { fetchChecksumFile, httpRequest } = await loadFresh()
    httpRequest.mockResolvedValueOnce(
      makeResponse({ ok: true, body: `${HASH_A}  file.zip\n` }),
    )
    const result = await fetchChecksumFile('https://example.com/checksums.txt')
    expect(result).toEqual({ 'file.zip': INT_A })
  })

  test('passes ca / headers / timeout through to httpRequest', async () => {
    const { fetchChecksumFile, httpRequest } = await loadFresh()
    httpRequest.mockResolvedValueOnce(makeResponse({ ok: true, body: '' }))
    await fetchChecksumFile('https://example.com/checksums.txt', {
      ca: ['fake-ca'],
      headers: { Authorization: 'Bearer x' },
      timeout: 5000,
    })
    const [, opts] = httpRequest.mock.calls[0]!
    expect(opts.ca).toEqual(['fake-ca'])
    expect(opts.headers).toEqual({ Authorization: 'Bearer x' })
    expect(opts.timeout).toBe(5000)
  })

  test('throws when the response is not ok', async () => {
    const { fetchChecksumFile, httpRequest } = await loadFresh()
    httpRequest.mockResolvedValueOnce(
      makeResponse({ ok: false, status: 404, body: '' }),
    )
    await expect(
      fetchChecksumFile('https://example.com/checksums.txt'),
    ).rejects.toThrow(/Failed to fetch checksums.*404 Error/)
  })

  test('returns empty object when response body is empty', async () => {
    const { fetchChecksumFile, httpRequest } = await loadFresh()
    httpRequest.mockResolvedValueOnce(makeResponse({ ok: true, body: '' }))
    expect(
      await fetchChecksumFile('https://example.com/checksums.txt'),
    ).toEqual({})
  })
})
