/**
 * @fileoverview Generate docs/api-index.md from package.json exports.
 * Walks every subpath export, finds the matching source file under src/, and
 * emits a grouped markdown table with the first line of each module's
 * `@fileoverview`. Regenerate whenever exports change.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootPath = path.join(__dirname, '..', '..')

type PackageExports = Record<
  string,
  string | { types?: string; default?: string } | undefined
>

type Row = { subpath: string; file: string; summary: string }

function extractSummary(srcPath: string): string {
  let content: string
  try {
    content = readFileSync(srcPath, 'utf8')
  } catch {
    return ''
  }
  const match = content.match(/\/\*\*([\s\S]*?)\*\//)
  if (!match) {
    return ''
  }
  const block = match[1] ?? ''
  const overviewIdx = block.indexOf('@fileoverview')
  if (overviewIdx < 0) {
    return ''
  }
  const afterTag = block.slice(overviewIdx + '@fileoverview'.length)
  // Strip leading-asterisk continuation and collapse whitespace.
  const flat = afterTag
    .split('\n')
    .map(line => line.replace(/^\s*\*\s?/, ''))
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim()
  // Stop at the first JSDoc tag (lines starting with `@` after normalization).
  const tagBoundary = flat.search(/\s@\w+/)
  const trimmed = (tagBoundary > 0 ? flat.slice(0, tagBoundary) : flat).trim()
  // First sentence, up to a period or 220 chars.
  const dotIdx = trimmed.indexOf('. ')
  if (dotIdx > 0 && dotIdx < 220) {
    return trimmed.slice(0, dotIdx + 1)
  }
  return trimmed.length > 220 ? `${trimmed.slice(0, 217)}...` : trimmed
}

function buildRows(exports: PackageExports): Row[] {
  const rows: Row[] = []
  for (const [subpath, value] of Object.entries(exports)) {
    if (subpath === '.' || subpath === './index' || subpath.endsWith('.json')) {
      continue
    }
    if (typeof value === 'string' || !value || !value.default) {
      continue
    }
    const def = value.default
    if (!def.startsWith('./dist/')) {
      continue
    }
    const srcPath = def
      .replace(/^\.\/dist\//, path.join(rootPath, 'src') + path.sep)
      .replace(/\.js$/, '.ts')
    const display = subpath.slice(2)
    rows.push({
      subpath: display,
      file: path.relative(rootPath, srcPath).replaceAll(path.sep, '/'),
      summary: extractSummary(srcPath),
    })
  }
  rows.sort((a, b) => a.subpath.localeCompare(b.subpath))
  return rows
}

function groupRows(rows: Row[]): Map<string, Row[]> {
  const groups = new Map<string, Row[]>()
  for (const row of rows) {
    const key = row.subpath.includes('/')
      ? `${row.subpath.split('/')[0]}/`
      : 'Top-level'
    const bucket = groups.get(key) ?? []
    bucket.push(row)
    groups.set(key, bucket)
  }
  return groups
}

function renderMarkdown(groups: Map<string, Row[]>): string {
  const keys = [...groups.keys()].sort((a, b) => {
    if (a === 'Top-level') {
      return -1
    }
    if (b === 'Top-level') {
      return 1
    }
    return a.localeCompare(b)
  })

  const lines: string[] = []
  lines.push('# API Index')
  lines.push('')
  lines.push(
    'Every subpath exported by **@socketsecurity/lib**, grouped by namespace.',
  )
  lines.push(
    'Each entry links to the source module and shows the first sentence of its `@fileoverview`.',
  )
  lines.push('')
  lines.push(
    '> Regenerate with `node scripts/fix/generate-api-index.mts` after adding or removing exports. Do not edit this file by hand.',
  )
  lines.push('')

  const jumpLinks = keys.map(key => {
    const anchor = key
      .toLowerCase()
      .replaceAll(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
    return `[${key}](#${anchor})`
  })
  lines.push(`**Jump to:** ${jumpLinks.join(' · ')}`)
  lines.push('')

  for (const key of keys) {
    lines.push(`## ${key}`)
    lines.push('')
    lines.push('| Subpath | Description |')
    lines.push('| --- | --- |')
    for (const row of groups.get(key) ?? []) {
      const summary = row.summary || '_(no description)_'
      lines.push(
        `| [\`@socketsecurity/lib/${row.subpath}\`](../${row.file}) | ${summary} |`,
      )
    }
    lines.push('')
  }

  return lines.join('\n')
}

function main(): void {
  const pkg = JSON.parse(
    readFileSync(path.join(rootPath, 'package.json'), 'utf8'),
  ) as { exports: PackageExports }

  const rows = buildRows(pkg.exports)
  const groups = groupRows(rows)
  const markdown = renderMarkdown(groups)
  const outPath = path.join(rootPath, 'docs', 'api-index.md')
  writeFileSync(outPath, markdown)
  // eslint-disable-next-line no-console
  console.log(`Wrote ${rows.length} exports to docs/api-index.md`)
}

main()
