/**
 * @file Resolve a binary path to the underlying script file.
 *   Wrapper-script unwrapping: a binary like `npm` is rarely an executable — on
 *   Windows it is `npm.cmd` / `npm.ps1` / an extensionless shell script. Each
 *   wrapper variant has a fixed format generated by either the npm CLI build
 *   (npm/npx specific) or by `cmd-shim` for arbitrary package binaries. The
 *   parsers in `resolve-shims.mts` extract the relative path to the underlying
 *   `.js` so callers can spawn Node with that path directly, which is cheaper
 *   than re-launching a shell wrapper.
 *   Volta managed installs are handled in `resolve-volta.mts`, which walks
 *   `~/.volta/tools/{image,user}/...` to the real CLI script and memoizes the
 *   result. That cache lives in `../shared.mjs` so `which.mts` can flush it
 *   when its own cache eviction fires.
 *   Cycles with `which.mts`: `normalizedBinPath` calls `whichRealSync` to
 *   handle relative input paths. ESM tolerates the cycle since both sides
 *   expose only functions, so no eager top-level evaluation needs the other
 *   module's bindings.
 */

import { isWin32 } from '../../constants/platform.mjs'
import { normalizePath } from '../../paths/normalize.mjs'
import { getFs, getPath } from '../shared.mjs'
import {
  isKnownShimExtension,
  isNodeBinName,
  isNpmOrNpxBin,
  isPnpmOrYarnBin,
} from './bin-kinds.mjs'
import { posixShimRelPath, windowsShimRelPath } from './resolve-shims.mjs'
import { resolveVoltaBinSync } from './resolve-volta.mjs'
import { whichRealSync } from './which.mjs'

/**
 * One bin path with the facts every resolution step branches on.
 */
export type BinPathFacts = {
  basename: string
  binPath: string
  extLowered: string
}

/**
 * An absolute, normalized form of a bin path. A relative input is looked up on
 * PATH first, since every later step pattern-matches an absolute layout.
 */
export function normalizedBinPath(binPath: string): string {
  const path = getPath()
  if (path.isAbsolute(binPath)) {
    return normalizePath(binPath)
  }
  try {
    const resolved = whichRealSync(binPath)
    if (resolved) {
      return normalizePath(resolved as string)
    }
  } catch {}
  return normalizePath(binPath)
}

/**
 * The npm/npx CLI script reachable directly from a bin directory, as installed
 * by the official Node.js Windows installer: `C:\Program Files\nodejs\npm.cmd`
 * sits beside `node_modules/npm/bin/npm-cli.js`. Returns `''` when that layout
 * does not apply, in which case the wrapper's body has to be parsed.
 */
export function npmWindowsQuickCliPath(config: BinPathFacts): string {
  const { basename, binPath, extLowered } = config
  if (!isKnownShimExtension(extLowered) || !isNpmOrNpxBin(basename)) {
    return ''
  }
  const fs = getFs()
  const path = getPath()
  const quickPath = path.join(
    path.dirname(binPath),
    `node_modules/npm/bin/${basename}-cli.js`,
  )
  if (!fs.existsSync(quickPath)) {
    return ''
  }
  try {
    return fs.realpathSync.native(quickPath)
  } catch {}
  return quickPath
}

/**
 * A path with symlinks followed, falling back to the normalized input when the
 * target does not exist.
 */
export function realOrNormalizedPath(binPath: string): string {
  const fs = getFs()
  try {
    return normalizePath(fs.realpathSync.native(binPath))
  } catch {}
  return normalizePath(binPath)
}

/**
 * The setup-pnpm GitHub Action can leave a bin path with extra segments, like
 * `<dir>/.bin/pnpm/bin/pnpm.cjs`, when the shell script's relative path
 * resolves into an invalid nested structure. Truncating at `/.bin/pnpm` names
 * the real shell script.
 *
 * The check below needs `statSync`, not `existsSync`: the discriminator is
 * `isFile()`, because the malformed path can also resolve to a directory.
 */
export function repairMalformedPnpmBinPath(binPath: string): string {
  const fs = getFs()
  const binMarker = '/.bin/pnpm'
  if (!binPath.includes(`${binMarker}/bin/`)) {
    return binPath
  }
  const binIndex = binPath.indexOf(binMarker)
  if (binIndex === -1) {
    return binPath
  }
  const baseBinPath = binPath.slice(0, binIndex + binMarker.length)
  try {
    // oxlint-disable-next-line socket/prefer-exists-sync -- needs isFile()
    if (fs.statSync(baseBinPath).isFile()) {
      return normalizePath(baseBinPath)
    }
  } catch {}
  return binPath
}

/**
 * A Unix shell wrapper resolved to the script it executes, or the input path
 * when it carries an extension or does not match a known wrapper format.
 */
export function resolvePosixWrapperPath(config: BinPathFacts): string {
  const { basename, extLowered } = config
  const fs = getFs()
  const path = getPath()
  const isWrapperBin = isPnpmOrYarnBin(basename) || isNpmOrNpxBin(basename)
  const binPath = isPnpmOrYarnBin(basename)
    ? repairMalformedPnpmBinPath(config.binPath)
    : config.binPath
  // Recomputed rather than reused: repairing the path can change the extension.
  const hasNoExt = !path.extname(binPath)
  // Verify existence before reading so a missing bin path is not an ENOENT.
  if (!hasNoExt || !isWrapperBin || !fs.existsSync(binPath)) {
    return binPath
  }
  const relPath = posixShimRelPath({
    basename,
    extLowered,
    source: fs.readFileSync(binPath, 'utf8'),
  })
  if (!relPath) {
    return binPath
  }
  // Resolved, not joined, so `..` segments collapse.
  return normalizePath(path.resolve(path.dirname(binPath), relPath))
}

/**
 * Resolve a binary path to the real underlying script file. Handles Windows
 * .cmd wrappers and Unix shell scripts, resolving them to the actual .js files
 * they execute.
 *
 * @example
 *   ;```typescript
 *   const realPath = resolveRealBinSync('/usr/local/bin/npm')
 *   // e.g. '/usr/local/lib/node_modules/npm/bin/npm-cli.js'
 *   ```
 */
export function resolveRealBinSync(binPath: string): string {
  const path = getPath()
  binPath = normalizedBinPath(binPath)
  // An empty string normalizes to '.', the current directory.
  if (binPath === '.') {
    return binPath
  }
  const ext = path.extname(binPath)
  const extLowered = ext.toLowerCase()
  const basename = path.basename(binPath, ext)
  const voltaIndex = voltaSegmentIndex({ basename, binPath })
  if (voltaIndex !== -1) {
    const voltaBinPath = resolveVoltaBinSync({ basename, binPath, voltaIndex })
    if (voltaBinPath) {
      return voltaBinPath
    }
  }
  const facts: BinPathFacts = { basename, binPath, extLowered }
  /* c8 ignore start - Windows-only wrapper resolution; tested on Windows runners. */
  if (isWin32()) {
    const quickPath = npmWindowsQuickCliPath(facts)
    if (quickPath) {
      return quickPath
    }
    return realOrNormalizedPath(resolveWindowsWrapperPath(facts))
  }
  /* c8 ignore stop */
  return realOrNormalizedPath(resolvePosixWrapperPath(facts))
}

/**
 * A Windows wrapper resolved to the script it executes, or the input path when
 * it is already an executable or does not match a known wrapper format.
 */
export function resolveWindowsWrapperPath(config: BinPathFacts): string {
  const { basename, binPath, extLowered } = config
  const fs = getFs()
  const path = getPath()
  // `.exe` files are executables already; there is no wrapper body to read.
  if (
    !isKnownShimExtension(extLowered) ||
    extLowered === '.exe' ||
    // Check existence before reading so a missing shim is not an ENOENT throw.
    !fs.existsSync(binPath)
  ) {
    return binPath
  }
  const relPath = windowsShimRelPath({
    basename,
    extLowered,
    source: fs.readFileSync(binPath, 'utf8'),
  })
  if (!relPath) {
    return binPath
  }
  return normalizePath(path.resolve(path.dirname(binPath), relPath))
}

/**
 * The offset of the `.volta/` segment in a bin path, or -1 when Volta does not
 * manage it.
 *
 * The Node binary itself is excluded: Volta's `node` entry is a shim that must
 * be spawned as-is, so walking into the image directory would break it.
 */
export function voltaSegmentIndex(config: {
  basename: string
  binPath: string
}): number {
  const { basename, binPath } = config
  if (isNodeBinName(basename)) {
    return -1
  }
  // require-regex-comment: locates a `/.volta/` path segment, case-insensitively.
  return /(?<=\/)\.volta\//i.exec(normalizePath(binPath))?.index ?? -1
}
