/**
 * @file Build, read, and write the two inventories the drift diff compares:
 *   the generated projection of npm's pinned spec, and the AST read of
 *   `src/npm/registry/*.mts`.
 *   The spec inventory is COMMITTED and GENERATED. Committing it is what lets
 *   the check run with no network and no cache - a fresh CI checkout still
 *   knows exactly which endpoints the pinned spec declares. Generating it is
 *   what keeps it honest: it is rewritten wholesale by
 *   `scripts/repo/sync-npm-api-spec.mts`, never hand-edited, and the banner
 *   inside it says so.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { spawn } from '@socketsecurity/lib-stable/process/spawn/child'
import { WIN32 } from '@socketsecurity/lib-stable/constants/platform'

import { REPO_ROOT } from '../../fleet/paths.mts'
import { readHelperModule } from './helper-ast.mts'
import { SPEC_INVENTORY_PATH } from './pin.mts'
import { collectEndpoints, parseSpecDocuments } from './spec-model.mts'
import { specIntegrityOf } from './spec-fetch.mts'

import type { HelperModule } from './helper-ast.mts'
import type { FetchedSpec } from './spec-fetch.mts'
import type { SpecEndpoint, SpecInventory } from './spec-model.mts'

/**
 * The banner every generated inventory carries. Read back by the sync script's
 * own tests, and by anyone who opens the file wondering whether to edit it.
 */
export const GENERATED_BANNER =
  'GENERATED by scripts/repo/sync-npm-api-spec.mts from the pinned npm/api-documentation spec. Do not hand-edit.'

/**
 * Where the helper modules live. Every `.mts` directly inside is a helper, so
 * the read needs no filename prefix: the directory IS the selector. The
 * `tarball/` subdirectory is out of scope — it reads archive bytes rather than
 * calling a registry endpoint, and the extension test skips it.
 */
export const HELPER_DIR = path.join(REPO_ROOT, 'src', 'npm', 'registry')

/**
 * How a helper module's file is labelled in the report, relative to the repo
 * root. Joined with the module's basename by the renderer.
 */
export const HELPER_DIR_LABEL = 'src/npm/registry'

/**
 * Where to read helper modules from. Tests point this at a scratch directory.
 */
export interface ReadHelperModulesOptions {
  helperDir?: string | undefined
}

/**
 * The on-disk shape of the generated inventory.
 */
export interface SpecInventoryFile {
  readonly '//': string
  readonly endpoints: readonly SpecEndpoint[]
  readonly sha: string
  readonly specIntegrity: string
}

/**
 * Which inventory file to read or write. Tests point this at a scratch file.
 */
export interface SpecInventoryPathOptions {
  inventoryPath?: string | undefined
}

/**
 * Project a fetched spec into the inventory the diff consumes.
 */
export function buildSpecInventory(spec: FetchedSpec): SpecInventory {
  return {
    endpoints: collectEndpoints(parseSpecDocuments(spec.files)),
    sha: spec.sha,
    specIntegrity: specIntegrityOf(spec),
  }
}

/**
 * Every `src/npm/registry/*.mts` read as an AST. A module that will not parse
 * is skipped, so one bad file degrades the report rather than killing it.
 */
export function readHelperModules(
  options?: ReadHelperModulesOptions | undefined,
): HelperModule[] {
  const opts = { __proto__: null, ...options } as ReadHelperModulesOptions
  const helperDir = opts.helperDir ?? HELPER_DIR
  const out: HelperModule[] = []
  const names = readdirSync(helperDir)
    .filter(name => name.endsWith('.mts'))
    .toSorted()
  for (let i = 0, { length } = names; i < length; i += 1) {
    const name = names[i]!
    const module = readHelperModule(
      name,
      readFileSync(path.join(helperDir, name), 'utf8'),
    )
    if (module) {
      out.push(module)
    }
  }
  return out
}

/**
 * The committed inventory, or undefined when it is absent or unreadable.
 */
export function readSpecInventory(
  options?: SpecInventoryPathOptions | undefined,
): SpecInventory | undefined {
  const opts = { __proto__: null, ...options } as SpecInventoryPathOptions
  const inventoryPath = opts.inventoryPath ?? SPEC_INVENTORY_PATH
  let parsed: unknown
  try {
    parsed = JSON.parse(readFileSync(inventoryPath, 'utf8'))
  } catch {
    return undefined
  }
  if (typeof parsed !== 'object' || parsed === null) {
    return undefined
  }
  const file = parsed as Partial<SpecInventoryFile>
  if (!Array.isArray(file.endpoints) || typeof file.sha !== 'string') {
    return undefined
  }
  return {
    endpoints: file.endpoints,
    sha: file.sha,
    specIntegrity:
      typeof file.specIntegrity === 'string' ? file.specIntegrity : '',
  }
}

/**
 * Run the repo formatter over the files a refresh just wrote.
 *
 * Generated output is still format-gated here, same as `make-api-md.mts`'s
 * docs: without this, `JSON.stringify`'s always-expanded arrays disagree with
 * oxfmt's collapse-if-it-fits rule and `lint --all` goes red on every refresh.
 * Best effort - a missing oxfmt must not fail a refresh.
 */
export async function formatGeneratedFiles(
  files: readonly string[],
): Promise<void> {
  try {
    await spawn(
      // Windows needs the .cmd shim: the extension-less .bin file is a POSIX
      // sh script cmd.exe cannot run.
      WIN32 ? 'node_modules\\.bin\\oxfmt.cmd' : 'node_modules/.bin/oxfmt',
      [
        '-c',
        '.config/fleet/oxfmtrc.json',
        '--ignore-path',
        '.config/fleet/.prettierignore',
        '--write',
        ...files,
      ],
      { cwd: REPO_ROOT, shell: WIN32, stdio: 'ignore' },
    )
  } catch {
    // Formatting is best effort — a refresh still wrote correct bytes.
  }
}

/**
 * Write the generated inventory, banner first.
 */
export function writeSpecInventory(
  inventory: SpecInventory,
  options?: SpecInventoryPathOptions | undefined,
): void {
  const opts = { __proto__: null, ...options } as SpecInventoryPathOptions
  const inventoryPath = opts.inventoryPath ?? SPEC_INVENTORY_PATH
  const file: SpecInventoryFile = {
    '//': GENERATED_BANNER,
    endpoints: inventory.endpoints,
    sha: inventory.sha,
    specIntegrity: inventory.specIntegrity,
  }
  writeFileSync(inventoryPath, `${JSON.stringify(file, undefined, 2)}\n`)
}
