import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'

import {
  buildBlock,
  clear,
  escapeRegExp,
  pickRcFile,
  shellSingleQuote,
  write,
  writeRcFile,
} from '../../../src/secrets/rc'

const IS_DARWIN = os.platform() === 'darwin'

let tmpRoot: string

beforeEach(() => {
  tmpRoot = mkdtempSync(path.join(os.tmpdir(), 'rc-test-'))
})

afterEach(() => {
  rmSync(tmpRoot, { force: true, recursive: true })
  vi.unstubAllEnvs()
})

describe.sequential('escapeRegExp', () => {
  test('escapes regex metacharacters', () => {
    expect(escapeRegExp('a.b*c+d?e^f$g{h}i(j)k|l[m]n\\o')).toBe(
      'a\\.b\\*c\\+d\\?e\\^f\\$g\\{h\\}i\\(j\\)k\\|l\\[m\\]n\\\\o',
    )
  })

  test('leaves plain text alone', () => {
    expect(escapeRegExp('hello world')).toBe('hello world')
  })

  test('handles empty string', () => {
    expect(escapeRegExp('')).toBe('')
  })
})

describe.sequential('shellSingleQuote', () => {
  test('wraps a plain string in single quotes', () => {
    expect(shellSingleQuote('hello')).toBe(`'hello'`)
  })

  test('escapes internal single quotes via POSIX-safe pattern', () => {
    expect(shellSingleQuote(`it's`)).toBe(`'it'\\''s'`)
  })

  test('handles multiple internal single quotes', () => {
    expect(shellSingleQuote(`a'b'c`)).toBe(`'a'\\''b'\\''c'`)
  })

  test('handles empty string', () => {
    expect(shellSingleQuote('')).toBe(`''`)
  })

  test('round-trips a value with special chars', () => {
    expect(shellSingleQuote('val with $vars and "double" quotes')).toBe(
      `'val with $vars and "double" quotes'`,
    )
  })
})

describe.sequential('buildBlock', () => {
  test('produces a BEGIN/END block with a single export line', () => {
    const { begin, body, end, full } = buildBlock({
      service: 'my-service',
      exports: { MY_VAR: 'hello' },
    })
    expect(begin).toBe('# BEGIN my-service env (managed)')
    expect(end).toBe('# END my-service env (managed)')
    expect(body).toBe(`export MY_VAR='hello'`)
    expect(full).toBe(
      `# BEGIN my-service env (managed)\nexport MY_VAR='hello'\n# END my-service env (managed)`,
    )
  })

  test('prepends note lines as `# ` comments', () => {
    const { body } = buildBlock({
      service: 's',
      exports: { X: '1' },
      notes: ['Rotate via: foo --rotate', 'Generated by foo at install.'],
    })
    expect(body).toBe(
      `# Rotate via: foo --rotate\n# Generated by foo at install.\nexport X='1'`,
    )
  })

  test('handles multiple exports', () => {
    const { body } = buildBlock({
      service: 's',
      exports: { A: '1', B: '2' },
    })
    expect(body).toBe(`export A='1'\nexport B='2'`)
  })

  test('escapes single quotes inside values', () => {
    const { body } = buildBlock({
      service: 's',
      exports: { Q: `it's` },
    })
    expect(body).toBe(`export Q='it'\\''s'`)
  })

  test('handles empty exports', () => {
    const { body } = buildBlock({ service: 's', exports: {} })
    expect(body).toBe('')
  })
})

describe.sequential('pickRcFile', () => {
  test('returns ~/.zshenv when explicit shell=zsh', () => {
    vi.stubEnv('HOME', '/tmp/fakehome')
    expect(pickRcFile('zsh')).toBe(path.join('/tmp/fakehome', '.zshenv'))
  })

  test('returns ~/.config/fish/config.fish when explicit shell=fish', () => {
    vi.stubEnv('HOME', '/tmp/fakehome')
    expect(pickRcFile('fish')).toBe(
      path.join('/tmp/fakehome', '.config', 'fish', 'config.fish'),
    )
  })

  test('returns bashrc when it exists', () => {
    vi.stubEnv('HOME', tmpRoot)
    writeFileSync(path.join(tmpRoot, '.bashrc'), '')
    expect(pickRcFile('bash')).toBe(path.join(tmpRoot, '.bashrc'))
  })

  test('falls back to .bash_profile when .bashrc is absent', () => {
    vi.stubEnv('HOME', tmpRoot)
    writeFileSync(path.join(tmpRoot, '.bash_profile'), '')
    expect(pickRcFile('bash')).toBe(path.join(tmpRoot, '.bash_profile'))
  })

  test('returns .bashrc (will be created later) when neither bash file exists', () => {
    vi.stubEnv('HOME', tmpRoot)
    expect(pickRcFile('bash')).toBe(path.join(tmpRoot, '.bashrc'))
  })

  test('reads SHELL env var when no override is provided (zsh)', () => {
    vi.stubEnv('HOME', '/tmp/fakehome')
    vi.stubEnv('SHELL', '/bin/zsh')
    expect(pickRcFile()).toBe(path.join('/tmp/fakehome', '.zshenv'))
  })

  test('reads SHELL env var when no override is provided (bash)', () => {
    vi.stubEnv('HOME', tmpRoot)
    vi.stubEnv('SHELL', '/usr/local/bin/bash')
    writeFileSync(path.join(tmpRoot, '.bashrc'), '')
    expect(pickRcFile()).toBe(path.join(tmpRoot, '.bashrc'))
  })

  test('returns undefined when shell is unknown', () => {
    vi.stubEnv('HOME', '/tmp/fakehome')
    vi.stubEnv('SHELL', '/usr/local/bin/exotic-shell')
    expect(pickRcFile()).toBeUndefined()
  })
})

describe.sequential('writeRcFile', () => {
  test('writes content with 0o600 mode', () => {
    const rcPath = path.join(tmpRoot, '.rcfile')
    writeRcFile(rcPath, 'hello')
    expect(readFileSync(rcPath, 'utf8')).toBe('hello')
    const { statSync } = require('node:fs') as typeof import('node:fs')
    const mode = statSync(rcPath).mode & 0o777
    expect(mode).toBe(0o600)
  })

  test('overwrites an existing file', () => {
    const rcPath = path.join(tmpRoot, '.rcfile')
    writeFileSync(rcPath, 'old')
    writeRcFile(rcPath, 'new')
    expect(readFileSync(rcPath, 'utf8')).toBe('new')
  })
})

describe.sequential('write (rc-file insertion)', () => {
  // The write/clear functions are darwin-gated. Skip on non-darwin to
  // avoid testing the early-return-undefined branch only.
  if (!IS_DARWIN) {
    test.skip('darwin-only', () => {})
    return
  }

  test('inserts a new block into a fresh rc file', () => {
    const rcPath = path.join(tmpRoot, '.zshenv')
    const result = write({
      service: 'my-svc',
      exports: { TOK: 'abc' },
      rcPath,
    })
    expect(result.outcome).toBe('inserted')
    if (result.outcome === 'inserted') {
      expect(result.rcPath).toBe(rcPath)
    }
    const content = readFileSync(rcPath, 'utf8')
    expect(content).toContain('# BEGIN my-svc env (managed)')
    expect(content).toContain(`export TOK='abc'`)
    expect(content).toContain('# END my-svc env (managed)')
  })

  test('returns "unchanged" when the block is already canonical', () => {
    const rcPath = path.join(tmpRoot, '.zshenv')
    write({ service: 'my-svc', exports: { TOK: 'abc' }, rcPath })
    const second = write({ service: 'my-svc', exports: { TOK: 'abc' }, rcPath })
    expect(second.outcome).toBe('unchanged')
  })

  test('returns "updated" when the exports change', () => {
    const rcPath = path.join(tmpRoot, '.zshenv')
    write({ service: 'my-svc', exports: { TOK: 'abc' }, rcPath })
    const updated = write({
      service: 'my-svc',
      exports: { TOK: 'new-value' },
      rcPath,
    })
    expect(updated.outcome).toBe('updated')
    expect(readFileSync(rcPath, 'utf8')).toContain(`export TOK='new-value'`)
  })

  test('preserves unrelated lines around the managed block', () => {
    const rcPath = path.join(tmpRoot, '.zshenv')
    writeFileSync(rcPath, '# user content\nexport USER_VAR=1\n')
    write({ service: 'my-svc', exports: { TOK: 'abc' }, rcPath })
    const content = readFileSync(rcPath, 'utf8')
    expect(content).toContain('export USER_VAR=1')
    expect(content).toContain(`export TOK='abc'`)
  })

  test('sweeps legacySentinels before inserting the new block', () => {
    const rcPath = path.join(tmpRoot, '.zshenv')
    writeFileSync(
      rcPath,
      '# BEGIN old-name env (managed)\nexport TOK=old\n# END old-name env (managed)\n',
    )
    write({
      service: 'new-name',
      exports: { TOK: 'abc' },
      legacySentinels: ['# BEGIN old-name env (managed)'],
      rcPath,
    })
    const content = readFileSync(rcPath, 'utf8')
    expect(content).not.toContain('old-name')
    expect(content).toContain('new-name')
    expect(content).toContain(`export TOK='abc'`)
  })
})

describe.sequential('clear (rc-file removal)', () => {
  if (!IS_DARWIN) {
    test.skip('darwin-only', () => {})
    return
  }

  test('returns false when the rc file does not exist', () => {
    vi.stubEnv('HOME', tmpRoot)
    vi.stubEnv('SHELL', '/bin/zsh')
    expect(clear('my-svc')).toBe(false)
  })

  test('removes a managed block and returns true', () => {
    vi.stubEnv('HOME', tmpRoot)
    vi.stubEnv('SHELL', '/bin/zsh')
    const rcPath = path.join(tmpRoot, '.zshenv')
    write({ service: 'my-svc', exports: { TOK: 'abc' }, rcPath })
    expect(clear('my-svc')).toBe(true)
    const content = readFileSync(rcPath, 'utf8')
    expect(content).not.toContain('my-svc')
  })

  test('returns false when no managed block matches', () => {
    vi.stubEnv('HOME', tmpRoot)
    vi.stubEnv('SHELL', '/bin/zsh')
    const rcPath = path.join(tmpRoot, '.zshenv')
    writeFileSync(rcPath, '# unrelated content\n')
    expect(clear('my-svc')).toBe(false)
  })

  test('strips a legacy sentinel block', () => {
    vi.stubEnv('HOME', tmpRoot)
    vi.stubEnv('SHELL', '/bin/zsh')
    const rcPath = path.join(tmpRoot, '.zshenv')
    writeFileSync(
      rcPath,
      '# BEGIN legacy env (managed)\nexport L=1\n# END legacy env (managed)\n',
    )
    expect(clear('not-the-current-svc', ['# BEGIN legacy env (managed)'])).toBe(
      true,
    )
    expect(readFileSync(rcPath, 'utf8')).not.toContain('legacy')
  })
})
