/**
 * @file Generate docs/api.md from package.json exports. Walks every subpath
 *   export, finds the matching source file under src/, and emits a grouped
 *   markdown table with the first line of each module's `@fileoverview`.
 *   Regenerate whenever exports change.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { spawn } from '@socketsecurity/lib-stable/process/spawn/child'

// Repo root from the canonical paths module (1 path, 1 reference) — not a
// hand-walked `__dirname/../..`, which silently breaks when the file moves.
import { REPO_ROOT as rootPath } from '../fleet/paths.mts'

const logger = getDefaultLogger()
const WIN32 = process.platform === 'win32'

type PackageExports = Record<
  string,
  | string
  | { types?: string | undefined; default?: string | undefined }
  | undefined
>

type Row = { subpath: string; file: string; summary: string }

export function buildRows(exports: PackageExports): Row[] {
  const rows: Row[] = []
  for (const [subpath, value] of Object.entries(exports)) {
    if (subpath === '.' || subpath === './index' || subpath.endsWith('.json')) {
      continue
    }
    if (typeof value === 'string' || !value || !value.default) {
      continue
    }
    const def = value.default
    if (!def.startsWith('./dist/')) {
      continue
    }
    const srcPath = def
      .replace(/^\.\/dist\//, path.join(rootPath, 'src') + path.sep)
      .replace(/\.js$/, '.ts')
    const display = subpath.slice(2)
    rows.push({
      subpath: display,
      file: path.relative(rootPath, srcPath).replaceAll(path.sep, '/'),
      summary: extractSummary(srcPath),
    })
  }
  rows.sort((a, b) => a.subpath.localeCompare(b.subpath))
  return rows
}

export function extractSummary(srcPath: string): string {
  let content: string
  try {
    content = readFileSync(srcPath, 'utf8')
  } catch {
    return ''
  }
  const match = content.match(/\/\*\*([\s\S]*?)\*\//)
  if (!match) {
    return ''
  }
  const block = match[1] ?? ''
  const overviewIdx = block.indexOf('@fileoverview')
  if (overviewIdx < 0) {
    return ''
  }
  const afterTag = block.slice(overviewIdx + '@fileoverview'.length)
  // Strip leading-asterisk continuation and collapse whitespace.
  const flat = afterTag
    .split('\n')
    .map(line => line.replace(/^\s*\*\s?/, ''))
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim()
  // Stop at the first JSDoc tag (lines starting with `@` after normalization).
  const tagBoundary = flat.search(/\s@\w+/)
  const trimmed = (tagBoundary > 0 ? flat.slice(0, tagBoundary) : flat).trim()
  // First sentence, up to a period or 220 chars.
  const dotIdx = trimmed.indexOf('. ')
  if (dotIdx > 0 && dotIdx < 220) {
    return trimmed.slice(0, dotIdx + 1)
  }
  return trimmed.length > 220 ? `${trimmed.slice(0, 217)}...` : trimmed
}

export function groupRows(rows: Row[]): Map<string, Row[]> {
  const groups = new Map<string, Row[]>()
  for (let i = 0, { length } = rows; i < length; i += 1) {
    const row = rows[i]!
    const key = row.subpath.includes('/')
      ? `${row.subpath.split('/')[0]}/`
      : 'Top-level'
    const bucket = groups.get(key) ?? []
    bucket.push(row)
    groups.set(key, bucket)
  }
  return groups
}

export function renderMarkdown(groups: Map<string, Row[]>): string {
  const keys = [...groups.keys()].toSorted((a, b) => {
    if (a === 'Top-level') {
      return -1
    }
    if (b === 'Top-level') {
      return 1
    }
    return a.localeCompare(b)
  })

  const lines: string[] = []
  lines.push('# API')
  lines.push('')
  lines.push(
    'Every subpath exported by **@socketsecurity/lib-stable**, grouped by namespace.',
  )
  lines.push(
    'Each entry links to the source module and shows the first sentence of its `@fileoverview`.',
  )
  lines.push('')
  lines.push(
    '> Regenerate with `pnpm run docs` after adding or removing exports. Do not edit this file by hand.',
  )
  lines.push('')

  const jumpLinks = keys.map(key => {
    const anchor = key
      .toLowerCase()
      .replaceAll(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
    return `[${key}](#${anchor})`
  })
  lines.push(`**Jump to:** ${jumpLinks.join(' · ')}`)
  lines.push('')

  for (const key of keys) {
    lines.push(`## ${key}`)
    lines.push('')
    lines.push('| Subpath | Description |')
    lines.push('| --- | --- |')
    for (const row of groups.get(key) ?? []) {
      const summary = row.summary || '_(no description)_'
      lines.push(
        `| [\`@socketsecurity/lib-stable/${row.subpath}\`](../${row.file}) | ${summary} |`,
      )
    }
    lines.push('')
  }

  return lines.join('\n')
}

async function main(): Promise<void> {
  const pkg = JSON.parse(
    readFileSync(path.join(rootPath, 'package.json'), 'utf8'),
  ) as { exports: PackageExports }

  const rows = buildRows(pkg.exports)
  const groups = groupRows(rows)
  const markdown = renderMarkdown(groups)
  const outPath = path.join(rootPath, 'docs', 'api.md')
  writeFileSync(outPath, markdown)
  // Run oxfmt so the checked-in file matches the formatter's expectations
  // (table column alignment, etc.) — otherwise lint fails on every build.
  // Must pass -c so the fleet's oxfmtrc.json (single-quote, no-semi, table
  // alignment behaviour) wins over oxfmt's built-in default config.
  try {
    await spawn(
      // Windows needs the .cmd shim — the extension-less .bin file is a POSIX
      // sh script cmd.exe (shell: WIN32) can't run.
      WIN32 ? 'node_modules\\.bin\\oxfmt.cmd' : 'node_modules/.bin/oxfmt',
      [
        '-c',
        '.config/fleet/oxfmtrc.json',
        '--ignore-path',
        '.config/fleet/.prettierignore',
        '--write',
        outPath,
      ],
      {
        cwd: rootPath,
        shell: WIN32,
        stdio: 'ignore',
      },
    )
  } catch {
    // Formatting is best-effort — don't fail the build if oxfmt is missing.
  }
  logger.log(`Wrote ${rows.length} exports to docs/api.md`)
}

main().catch(err => {
  // eslint-disable-next-line no-console
  logger.fail(err)
  process.exitCode = 1
})
