// GENERATED by scripts/fleet/make-hook-dispatch.mts — do not edit by hand.
// Static dispatch table: every bundle-safe fleet hook, grouped by event.
// Re-run the maker after adding/removing an eligible hook, then rebuild
// the bundle with scripts/fleet/build-hook-bundle.mts.

import type { DispatchHookEntry } from './dispatch.mts'

import { run as run0 } from '../bundle-stale-reminder/index.mts'

export const DISPATCH_TABLE: Record<string, readonly DispatchHookEntry[]> = {
  __proto__: null,
  'PostToolUse': [
    { name: 'bundle-stale-reminder', run: run0, tools: ['Edit', 'Write'] },
  ],
} as Record<string, readonly DispatchHookEntry[]>
