#!/usr/bin/env node
/**
 * @file The single-process fleet hook dispatcher. Claude Code can invoke one
 *   `node _dispatch/index.cjs <Event>` per hook event instead of spawning a
 *   separate `node <hook>/index.mts` per hook. The loader (`index.cjs`) turns
 *   on the V8 compile cache, then requires the rolldown CJS bundle whose entry
 *   is THIS module's compiled form.
 *
 *   The dispatcher reads the event arg + stdin ONCE, then runs every bundled
 *   hook registered for that event from the STATIC dispatch table
 *   (`dispatch-table.mts`, generated by `scripts/fleet/make-hook-dispatch.mts`).
 *   A static table is what lets rolldown bundle the hooks: a dynamic
 *   `import(path.join(HOOKS_DIR, rel))` is opaque to the bundler.
 *
 *   Trigger pre-flight + early-exit: a bundled hook entry can declare the tool
 *   names it cares about; the dispatcher skips a hook whose tool doesn't match
 *   before importing/running it, so an unrelated event is a near no-op.
 *
 *   The bundled set is reminder-only today (the cutover from per-hook spawns is
 *   gated off in settings.json), so the dispatcher writes any reminder text to
 *   stderr and always exits 0. The block-signalling seam is present
 *   (`DispatchResult.decision`) for when blocking hooks are converted.
 */

import process from 'node:process'

import { readStdin } from '../_shared/transcript.mts'

import { DISPATCH_TABLE } from './dispatch-table.mts'

export interface DispatchPayload {
  readonly cwd?: string | undefined
  readonly hook_event_name?: string | undefined
  readonly tool_input?: Record<string, unknown> | undefined
  readonly tool_name?: string | undefined
  readonly transcript_path?: string | undefined
}

export interface DispatchHookEntry {
  /**
   * The hook leaf name (the `fleet/<name>` dir), for diagnostics.
   */
  readonly name: string
  /**
   * Tool names this hook handles. Empty/omitted means "any tool" (e.g. Stop
   * hooks). The dispatcher uses this for the trigger pre-flight early-exit.
   */
  readonly tools?: readonly string[] | undefined
  /**
   * The hook's pure entry. Returns reminder text to surface on stderr, or
   * `undefined` when there is nothing to say.
   */
  readonly run: (payload: DispatchPayload) => string | undefined
}

export interface DispatchResult {
  /**
   * `'block'` once blocking hooks are converted; today the bundled set is
   * reminder-only so this stays `'allow'`.
   */
  readonly decision: 'allow' | 'block'
  /**
   * Reminder lines collected from the hooks that fired.
   */
  readonly reminders: readonly string[]
}

/**
 * Returns true when the hook entry handles the payload's tool. An entry with
 * no declared tools handles every event (Stop / SessionStart style).
 */
export function hookHandlesTool(
  entry: DispatchHookEntry,
  toolName: string | undefined,
): boolean {
  if (!entry.tools || entry.tools.length === 0) {
    return true
  }
  if (!toolName) {
    return false
  }
  return entry.tools.includes(toolName)
}

/**
 * Run every bundled hook registered for `event` against `payload`. Pure: no
 * process I/O, so it is unit-testable and the bundler can tree-shake freely.
 */
export function dispatch(
  event: string,
  payload: DispatchPayload,
): DispatchResult {
  const entries = DISPATCH_TABLE[event] ?? []
  const reminders: string[] = []
  const toolName = payload.tool_name
  for (let i = 0, { length } = entries; i < length; i += 1) {
    const entry = entries[i]!
    if (!hookHandlesTool(entry, toolName)) {
      continue
    }
    let text: string | undefined
    try {
      text = entry.run(payload)
    } catch {
      // A misbehaving bundled hook must never wedge the whole dispatcher.
      text = undefined
    }
    if (text) {
      reminders.push(text)
    }
  }
  return { __proto__: null, decision: 'allow', reminders } as DispatchResult
}

/**
 * The dispatcher CLI: read the event arg (`process.argv[2]`) + stdin once, run
 * the bundled hooks, surface reminders on stderr, exit 0. Exported (not
 * auto-run) so the rolldown bundle entry (`dispatch-entry.mts`) can call it
 * unconditionally while unit tests / the source module stay import-safe — a
 * CJS bundle has no `import.meta`, so an entrypoint-guard can't gate it there.
 */
export async function runDispatcherCli(): Promise<void> {
  const event = process.argv[2]
  if (!event) {
    process.exit(0)
  }
  let raw: string
  try {
    raw = await readStdin()
  } catch {
    process.exit(0)
  }
  if (!raw.trim()) {
    process.exit(0)
  }
  let payload: DispatchPayload
  try {
    payload = JSON.parse(raw) as DispatchPayload
  } catch {
    process.exit(0)
  }
  const result = dispatch(event, payload)
  if (result.reminders.length) {
    process.stderr.write(result.reminders.join('\n') + '\n')
  }
  // Reminder-only bundled set: never blocks.
  process.exit(0)
}

// Direct `node dispatch.mts <Event>` execution (dev / test harness) runs the
// CLI; importing the module for its pure helpers does not.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  runDispatcherCli().catch(() => {
    process.exit(0)
  })
}
