/*
 * @file Build-out stubs for fleet-unused exports — the helper that
 *   manufactures a throwing stand-in for every export of a leaf module the
 *   fleet-usage audit proved unused, and the post-build pass that swaps the
 *   built dist modules for those stubs. The export NAMES survive (literal
 *   `exports.<name> =` assignments, so cjs-module-lexer still surfaces them
 *   to ESM named imports and the .d.mts surface stays truthful at compile
 *   time); the BODIES throw with the ask-to-expose message on first use.
 *
 *   The leaf list lives in the `buildStubs.unexposed` section of
 *   `.config/repo/socket-wheelhouse.json` — regenerated by
 *   `audit-fleet-lib-usage.mts --write-stub-list`, committed so the published
 *   build is reproducible without sibling checkouts.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { memberSettingsPath, readBuildStubs } from './settings.mts'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'

const logger = getDefaultLogger()

// First line of every generated stub — the idempotence marker the apply pass
// keys on, so re-running the build never double-stubs.
export const STUB_BANNER = '/* socket-lib build-stub: unexposed leaf */'

export const EXPOSE_ISSUE_URL = 'https://github.com/SocketDev/socket-lib/issues'

/**
 * The runtime export names of a built CJS dist module, read statically from
 * its `exports.<name> =` assignments. A module shaped `module.exports = x`
 * has no static name list — the caller must skip it loudly rather than
 * guess.
 */
export function collectRuntimeExportNames(distSource: string): string[] {
  const names = new Set<string>()
  const re = /^exports\.(?<name>[A-Za-z_$][\w$]*)\s*=/gm
  let m = re.exec(distSource)
  while (m !== null) {
    const name = m.groups?.['name']
    if (name) {
      names.add(name)
    }
    m = re.exec(distSource)
  }
  return [...names].toSorted()
}

/**
 * The generated stub module source for one leaf: every export keeps its
 * name; every use throws with the expose ask.
 */
export function makeUnexposedModuleSource(
  leaf: string,
  names: readonly string[],
): string {
  const assignments = names
    .map(name => `exports.${name} = unexposed(${JSON.stringify(name)});`)
    .join('\n')
  return `${STUB_BANNER}
'use strict';
// Generated by scripts/repo/build-stubs — no fleet consumer imports this
// leaf, so its implementation is compiled out of the published build.
function unexposed(name) {
  return function () {
    throw new Error(
      name + ' is compiled out of this @socketsecurity/lib build.\\n' +
      '  Where: @socketsecurity/lib/${leaf}\\n' +
      '  Saw: a call to a build-stubbed export; wanted the real implementation.\\n' +
      '  Fix: in a socket-lib checkout, run\\n' +
      '    node scripts/repo/expose-leaf.mts ${leaf}\\n' +
      '  which un-stubs the leaf, rebuilds, and commits. Then cut a release to\\n' +
      '  ship it. No socket-lib checkout? Open an issue at ${EXPOSE_ISSUE_URL}.'
    );
  };
}
${assignments}
`
}

/**
 * The path of the committed stub-leaf list.
 */
export function unexposedLeavesPath(repoRoot: string): string {
  return memberSettingsPath(repoRoot)
}

/**
 * The committed stub-leaf list.
 */
export function readUnexposedLeaves(repoRoot: string): string[] {
  return readBuildStubs(repoRoot).unexposed.leaves
}

/**
 * The roster the committed list was judged against, as recorded when it was
 * written. Empty when the list predates the record.
 *
 * "Unused" is a claim about the whole fleet, so the list is only as good as
 * the set of consumers actually scanned. Storing the conclusion without the
 * evidence makes a list computed against a smaller fleet indistinguishable
 * from a correct one, which is how a leaf only one member imports can stay
 * stubbed after that member joins. The writer refuses to run with a missing
 * checkout, but that guard cannot reach backwards into a list written before
 * it existed.
 */
export function readScannedRoster(repoRoot: string): string[] {
  return readBuildStubs(repoRoot).unexposed.scannedRoster
}

/**
 * How the committed list's recorded roster differs from the current one:
 * `missing` are members it was never judged against, `stale` are names it
 * records that have since left. Either means the evidence no longer covers
 * the fleet and the list must be regenerated, whatever any individual leaf
 * looks like today.
 *
 * Compares MEMBERSHIP, not each consumer's commit. Pinning commits would
 * invalidate the list on every unrelated push and train everyone to
 * regenerate on reflex; membership changes are rare and are exactly the event
 * that silently widens the set of importers.
 */
export function rosterCoverageGap(
  currentRoster: readonly string[],
  scannedRoster: readonly string[],
): { missing: string[]; stale: string[] } {
  const scanned = new Set(scannedRoster)
  const current = new Set(currentRoster)
  return {
    missing: currentRoster.filter(name => !scanned.has(name)).toSorted(),
    stale: scannedRoster.filter(name => !current.has(name)).toSorted(),
  }
}

// The dist .js target a leaf's exports-map entry points at, or undefined for
// non-JS targets (data files, wildcard entries).
function distTargetFor(
  exportsMap: Record<string, unknown>,
  leaf: string,
): string | undefined {
  const entry = exportsMap[`./${leaf}`]
  const target =
    typeof entry === 'string'
      ? entry
      : ((entry as { default?: string | undefined } | undefined)?.default ??
        undefined)
  return typeof target === 'string' && target.endsWith('.js')
    ? target
    : undefined
}

/**
 * Swap every listed leaf's built dist module for its stub. Idempotent; fails
 * loud when a listed leaf has no built dist file or no statically readable
 * export names.
 */
export function applyUnexposedStubs(repoRoot: string): {
  skipped: string[]
  stubbed: string[]
} {
  const manifest = JSON.parse(
    readFileSync(path.join(repoRoot, 'package.json'), 'utf8'),
  ) as { exports?: Record<string, unknown> | undefined }
  const exportsMap = manifest.exports ?? {}
  const leaves = readUnexposedLeaves(repoRoot)
  const stubbed: string[] = []
  const skipped: string[] = []
  for (let i = 0, { length } = leaves; i < length; i += 1) {
    const leaf = leaves[i] as string
    const target = distTargetFor(exportsMap, leaf)
    if (!target) {
      skipped.push(leaf)
      continue
    }
    const distPath = path.join(repoRoot, target)
    if (!existsSync(distPath)) {
      throw new Error(
        'build-stubs: a listed leaf has no built dist file.\n' +
          `  Where: ${target} (leaf ${leaf})\n` +
          '  Saw: the exports map names it but the build emitted nothing.\n' +
          '  Fix: rebuild first, or regenerate the list with audit-fleet-lib-usage.mts --write-stub-list.',
      )
    }
    const source = readFileSync(distPath, 'utf8')
    if (source.startsWith(STUB_BANNER)) {
      stubbed.push(leaf)
      continue
    }
    const names = collectRuntimeExportNames(source)
    if (names.length === 0) {
      // A `module.exports =` shaped module has no static names to preserve —
      // leave it real rather than break its import shape.
      skipped.push(leaf)
      continue
    }
    writeFileSync(distPath, makeUnexposedModuleSource(leaf, names))
    stubbed.push(leaf)
  }
  if (leaves.length > 0) {
    logger.info(
      `build-stubs: ${stubbed.length} leaf module(s) stubbed, ${skipped.length} skipped.`,
    )
  }
  return { skipped, stubbed }
}
