/**
 * @fileoverview Unit tests for src/eco/cargo/parse-lockfile.ts.
 */

import { describe, expect, it } from 'vitest'

import {
  extractCargoDepName,
  parseCargoGitSource,
  parseCargoLock,
  parseInlineArray,
  stripTomlString,
  valueAfterEquals,
} from '@socketsecurity/lib/eco/cargo/parse-lockfile'

const CARGO_LOCK_V3 = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "25dd9975e68d0cb5aa1120c288333fc98731331a01b7c2c30e2e3a85f1ebe93b"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "43576ca501357b9b071ac53cdc7da8ef0cbd9493d8df094cd821777ea6e894d3"
dependencies = [
 "proc-macro2",
 "quote",
 "syn 2.0.39",
]

[[package]]
name = "syn"
version = "1.0.103"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "fdb5bec1d9c2cf637a6041d5a08cc909006a3ef4f78bcd6a6c4cf66dee2cb1c0"

[[package]]
name = "syn"
version = "2.0.39"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "23e78b90f2fcf45d3e842032ce32e3f2d1545ba6636271dcbf24fa306d87be7a"
`

const CARGO_LOCK_GIT = `[[package]]
name = "foo"
version = "0.1.0"
source = "git+https://github.com/rust-lang/foo.git#abc123"
`

describe('eco/cargo/parse-lockfile', () => {
  describe('parseCargoLock', () => {
    const result = parseCargoLock(CARGO_LOCK_V3)

    it('reports cargo ecosystem', () => {
      expect(result.ecosystem).toBe('cargo')
    })

    it('flags lockVersion as "3"', () => {
      expect(result.lockVersion).toBe('3')
    })

    it('captures all four package entries', () => {
      expect(result.packages).toHaveLength(4)
    })

    it('extracts name, version, source, and checksum', () => {
      const serde = result.packages.find(
        p => p.name === 'serde' && p.version === '1.0.193',
      )!
      expect(serde.resolved).toBe(
        'registry+https://github.com/rust-lang/crates.io-index',
      )
      expect(serde.integrity).toBe(
        '25dd9975e68d0cb5aa1120c288333fc98731331a01b7c2c30e2e3a85f1ebe93b',
      )
      expect(serde.dependencies).toEqual(['serde_derive'])
    })

    it('strips version + source spec from dependency entries', () => {
      const derive = result.packages.find(p => p.name === 'serde_derive')!
      expect(derive.dependencies).toEqual(['proc-macro2', 'quote', 'syn'])
    })

    it('indexes multi-version names as arrays', () => {
      const synIdx = (result._index as { syn?: unknown })['syn']
      expect(Array.isArray(synIdx)).toBe(true)
      expect((synIdx as number[]).length).toBe(2)
    })

    it('extends the index array when a name has 3+ entries', () => {
      const lock = `[[package]]\nname = "foo"\nversion = "1.0.0"\n\n[[package]]\nname = "foo"\nversion = "2.0.0"\n\n[[package]]\nname = "foo"\nversion = "3.0.0"\n`
      const triple = parseCargoLock(lock)
      const fooIdx = (triple._index as { foo?: unknown })['foo']
      expect(Array.isArray(fooIdx)).toBe(true)
      expect(fooIdx).toEqual([0, 1, 2])
    })

    it('extracts git VCS metadata from a git+ source', () => {
      const git = parseCargoLock(CARGO_LOCK_GIT)
      const foo = git.packages.find(p => p.name === 'foo')!
      expect(foo.vcsUrl).toBe('git+https://github.com/rust-lang/foo.git')
      expect(foo.vcsCommit).toBe('abc123')
    })

    it('returns zero packages for empty content', () => {
      const result = parseCargoLock('')
      expect(result.packages).toEqual([])
    })

    it('ignores [metadata] and similar non-[[package]] sections', () => {
      const lock = `[metadata]\nfoo = "bar"\n\n[[package]]\nname = "x"\nversion = "1.0.0"\n`
      const result = parseCargoLock(lock)
      expect(result.packages.map(p => p.name)).toEqual(['x'])
    })

    it('ignores [[patch.unused]] table-of-arrays sections', () => {
      // Cargo 1.78+ emits `[[patch.unused]]` for patches that had no
      // effect. They share the table-array shape with `[[package]]` but
      // must NOT be treated as real deps.
      const lock = `[[package]]\nname = "real"\nversion = "1.0.0"\n\n[[patch.unused]]\nname = "shadow"\nversion = "2.0.0"\nsource = "registry+https://example.com"\n`
      const result = parseCargoLock(lock)
      expect(result.packages.map(p => p.name)).toEqual(['real'])
    })

    it('freezes the result and packages list', () => {
      expect(Object.isFrozen(result)).toBe(true)
      expect(Object.isFrozen(result.packages)).toBe(true)
      expect(Object.isFrozen(result.packages[0])).toBe(true)
    })
  })

  describe('inline-array dependencies', () => {
    it('parses single-line array', () => {
      const lock = `[[package]]\nname = "x"\nversion = "1.0.0"\ndependencies = [ "a", "b 1.0.0" ]\n`
      const result = parseCargoLock(lock)
      expect(result.packages[0]!.dependencies).toEqual(['a', 'b'])
    })

    it('returns [] for an empty single-line array', () => {
      const lock = `[[package]]\nname = "x"\nversion = "1.0.0"\ndependencies = []\n`
      const result = parseCargoLock(lock)
      expect(result.packages[0]!.dependencies).toEqual([])
    })
  })

  describe('helpers', () => {
    it('extractCargoDepName strips quotes + version', () => {
      expect(extractCargoDepName('"foo 1.2.3"')).toBe('foo')
      expect(extractCargoDepName('foo')).toBe('foo')
      expect(extractCargoDepName('"foo"')).toBe('foo')
    })

    it('parseCargoGitSource detects git+ scheme + commit', () => {
      expect(parseCargoGitSource('git+https://example.com/x.git#abc')).toEqual({
        url: 'git+https://example.com/x.git',
        commit: 'abc',
      })
    })

    it('parseCargoGitSource handles git+ without commit', () => {
      expect(parseCargoGitSource('git+https://example.com/x.git')).toEqual({
        url: 'git+https://example.com/x.git',
        commit: undefined,
      })
    })

    it('parseCargoGitSource returns undefined for non-git sources', () => {
      expect(parseCargoGitSource('registry+https://x')).toBe(undefined)
    })

    it('stripTomlString peels surrounding double quotes', () => {
      expect(stripTomlString('"hi"')).toBe('hi')
      expect(stripTomlString('hi')).toBe('hi')
    })

    it('valueAfterEquals returns text after the first =', () => {
      expect(valueAfterEquals('name = "foo"')).toBe('"foo"')
    })

    it('valueAfterEquals returns "" when no = present', () => {
      expect(valueAfterEquals('name')).toBe('')
    })

    it('parseInlineArray returns empty for malformed bounds', () => {
      expect(parseInlineArray('not an array')).toEqual([])
      expect(parseInlineArray('[]')).toEqual([])
    })

    it('parseInlineArray handles bare unquoted entries', () => {
      expect(parseInlineArray('[ foo, bar ]')).toEqual(['foo', 'bar'])
    })

    it('parseInlineArray stops on trailing whitespace + comma', () => {
      // Whitespace-only suffix after the last comma — loop exits via
      // the "i >= inner.length" break after the inner whitespace skip.
      expect(parseInlineArray('[ "a", "b",  ]')).toEqual(['a', 'b'])
    })

    it('parseInlineArray bails on an unterminated quoted entry', () => {
      // Opening quote without a matching closing quote — the loop
      // exits via the "closeIdx === -1" break, returning what we have.
      expect(parseInlineArray('[ "a", "unterminated ]')).toEqual(['a'])
    })
  })
})
