/**
 * @file Pure helpers for the primordial audit walk: source-file classification,
 *   line/column math, acorn parse options, and the AST-shape predicates that
 *   recognize bundler boilerplate and CJS interop glue. These have no
 *   dependency on the per-file walk state, so they live apart from the
 *   `auditDirectory` orchestrator in `audit.mts`.
 */

import path from 'node:path'

// File extensions the walker descends into. TypeScript files get
// type-stripped before parsing (acorn-wasm's `typescript: true` doesn't
// cover modern TS syntax: `export type`, class fields with annotations,
// generic type parameters, etc.). The strip-then-parse approach is
// reliable and uses only Node built-ins (`module.stripTypeScriptTypes`,
// available 22.6+).
export const TS_EXTENSIONS = new Set(['.cts', '.mts', '.ts', '.tsx'])
export const JS_EXTENSIONS = new Set(['.cjs', '.js', '.jsx', '.mjs'])

export const PARSE_OPTIONS = {
  allowAwaitOutsideFunction: true,
  allowHashBang: true,
  allowImportExportEverywhere: true,
  ecmaVersion: 'latest',
  locations: true,
  sourceType: 'module',
}

export function buildLineStarts(src) {
  const starts = [0]
  for (let i = 0; i < src.length; i += 1) {
    if (src.charCodeAt(i) === 10) {
      starts.push(i + 1)
    }
  }
  return starts
}

/**
 * Recognize esbuild's CJS-output boilerplate — the helper-variable
 * assignments at the top of every esbuild-bundled file: var __defProp =
 * Object.defineProperty; var __getOwnPropDesc =
 * Object.getOwnPropertyDescriptor; var __getOwnPropNames =
 * Object.getOwnPropertyNames; var __hasOwnProp =
 * Object.prototype.hasOwnProperty;
 *
 * These are machine-generated bundler plumbing, not user code. The tell is
 * that they're being assigned to a `__`-prefixed identifier inside a
 * `VariableDeclarator`. The helpers themselves use those locals, not the
 * original `Object.X` references — flagging the assignment is misleading
 * because there's nothing to migrate.
 */
export function isBundlerHelperAssignment(ancestors) {
  // ancestors are listed root-first; the immediate parent is the last entry.
  // Walk up looking for the nearest VariableDeclarator.
  for (let i = ancestors.length - 1; i >= 0; i -= 1) {
    const a = ancestors[i]
    if (a.type === 'VariableDeclarator') {
      return (
        a.id?.type === 'Identifier' &&
        typeof a.id.name === 'string' &&
        a.id.name.startsWith('__')
      )
    }
    // Don't cross function/program boundaries — only check the direct
    // VariableDeclarator if we're inside one.
    if (
      a.type === 'ArrowFunctionExpression' ||
      a.type === 'FunctionDeclaration' ||
      a.type === 'FunctionExpression' ||
      a.type === 'Program'
    ) {
      return false
    }
  }
  return false
}

// `.d.ts`, `.d.mts`, `.d.cts` are type-only declaration files — no
// runtime code, so they can never contain a primordial call site.
// `path.extname` returns just `.ts` for `foo.d.ts`, so we have to
// match against the basename's secondary suffix.
export function isDeclarationFile(absPath) {
  const base = path.basename(absPath)
  return /\.d\.[mc]?ts$/.test(base)
}

/**
 * Recognize esbuild/tsc CommonJS interop glue: Object.defineProperty(exports,
 * "__esModule", { value: true }) Object.defineProperty(module.exports, ...)
 * These are machine-generated by every bundler that emits CJS from ESM. They
 * aren't migration candidates — they're plumbing.
 */
export function isExportsInteropGlue(node) {
  if (node.callee?.type !== 'MemberExpression') {
    return false
  }
  const { object, property } = node.callee
  if (
    object?.type !== 'Identifier' ||
    object.name !== 'Object' ||
    property?.name !== 'defineProperty'
  ) {
    return false
  }
  const firstArg = node.arguments?.[0]
  if (!firstArg) {
    return false
  }
  // Object.defineProperty(exports, ...)
  if (firstArg.type === 'Identifier' && firstArg.name === 'exports') {
    return true
  }
  // Object.defineProperty(module.exports, ...)
  if (
    firstArg.type === 'MemberExpression' &&
    !firstArg.computed &&
    firstArg.object?.type === 'Identifier' &&
    firstArg.object.name === 'module' &&
    firstArg.property?.name === 'exports'
  ) {
    return true
  }
  return false
}

/**
 * Recognize the safe `Object.prototype.hasOwnProperty.call(target, key)`
 * idiom — that's already-correct hardening, not a migration target.
 *
 * Pattern: `Object.prototype.<method>.call(...)` where `<method>` is a method
 * on `Object.prototype` (`hasOwnProperty`, `propertyIsEnumerable`,
 * `isPrototypeOf`, `toString`, etc.). Reporting these as "Object.prototype"
 * findings is noise.
 */
export function isObjectPrototypeIdiom(node) {
  return (
    node.type === 'MemberExpression' &&
    !node.computed &&
    node.object?.type === 'MemberExpression' &&
    !node.object.computed &&
    node.object.object?.type === 'Identifier' &&
    node.object.object.name === 'Object' &&
    node.object.property?.name === 'prototype'
  )
}

/**
 * Returns true if the file's extension is one we walk.
 */
export function isSourceFile(absPath) {
  if (isDeclarationFile(absPath)) {
    return false
  }
  const ext = path.extname(absPath)
  return TS_EXTENSIONS.has(ext) || JS_EXTENSIONS.has(ext)
}

/**
 * Build a (start-of-line offset → 1-based line number) lookup for a source
 * string. acorn-wasm's `node.loc` is unreliable in our build (locations come
 * back undefined despite `locations: true`), so we compute line/column from
 * `node.start` (a 0-based byte offset) ourselves.
 */
export function lineColumnAt(lineStarts, offset) {
  // Binary search for the largest lineStarts entry ≤ offset.
  let lo = 0
  let hi = lineStarts.length - 1
  while (lo < hi) {
    const mid = (lo + hi + 1) >>> 1
    if (lineStarts[mid] <= offset) {
      lo = mid
    } else {
      hi = mid - 1
    }
  }
  return {
    line: lo + 1,
    column: offset - lineStarts[lo] + 1,
  }
}
